"""add media assets

Revision ID: 813ab8be29dc
Revises: e14321b14f71
Create Date: 2026-09-29 14:39:23.457164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '813ab8be29dc'
down_revision: Union[str, Sequence[str], None] = 'e14321b14f71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('storage_provider', sa.Text(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('media_type', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'READY', 'FAILED', name='media_asset_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_provider', 'storage_key', name='uq_media_assets_provider_storage_key')
    )
    op.add_column('product_media', sa.Column('media_asset_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_product_media_media_asset_id'), 'product_media', ['media_asset_id'], unique=False)
    op.create_foreign_key(None, 'product_media', 'media_assets', ['media_asset_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('product_media', 'media_type')
    op.drop_column('product_media', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_media', sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('product_media', sa.Column('media_type', postgresql.ENUM('IMAGE', 'VIDEO', name='media_type'), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'product_media', type_='foreignkey')
    op.drop_index(op.f('ix_product_media_media_asset_id'), table_name='product_media')
    op.drop_column('product_media', 'media_asset_id')
    op.drop_table('media_assets')
    # ### end Alembic commands ###
