"""add product id to upload sessions

Revision ID: ddd1a54f84cd
Revises: 9f9bf4d5a61b
Create Date: 2026-09-29 18:08:10.291739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddd1a54f84cd'
down_revision: Union[str, Sequence[str], None] = '9f9bf4d5a61b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_sessions', sa.Column('product_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'upload_sessions', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'upload_sessions', type_='foreignkey')
    op.drop_column('upload_sessions', 'product_id')
    # ### end Alembic commands ###
