"""initial schema

Revision ID: e14321b14f71
Revises: 
Create Date: 2026-09-29 02:45:28.382346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e14321b14f71'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_media_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='record_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_slug'), 'brands', ['slug'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='record_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('content_pages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='record_status'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_pages_slug'), 'content_pages', ['slug'], unique=True)
    op.create_index(op.f('ix_content_pages_status'), 'content_pages', ['status'], unique=False)
    op.create_table('inquiries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('inquiry_type', sa.Enum('GENERAL', 'PRODUCT', 'CUSTOMIZATION', 'OEM', 'ODM', 'PRIVATE_LABEL', 'WHOLESALE', name='inquiry_type'), nullable=False),
    sa.Column('quantity_range', sa.Enum('SAMPLE', 'SMALL_BATCH', 'WHOLESALE', 'LARGE_VOLUME', 'NOT_SURE', name='quantity_range'), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source_page', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'RESPONDED', 'CLOSED', name='inquiry_status'), nullable=False),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inquiries_inquiry_type'), 'inquiries', ['inquiry_type'], unique=False)
    op.create_index(op.f('ix_inquiries_status'), 'inquiries', ['status'], unique=False)
    op.create_table('collections',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_media_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='record_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'slug', name='uq_collections_brand_slug'),
    sa.UniqueConstraint('id', 'brand_id', name='uq_collections_id_brand')
    )
    op.create_index(op.f('ix_collections_brand_id'), 'collections', ['brand_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('product_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='record_status'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['collection_id', 'brand_id'], ['collections.id', 'collections.brand_id'], name='fk_products_collection_brand', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'product_code', name='uq_products_brand_product_code'),
    sa.UniqueConstraint('brand_id', 'slug', name='uq_products_brand_slug')
    )
    op.create_index(op.f('ix_products_brand_id'), 'products', ['brand_id'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_collection_id'), 'products', ['collection_id'], unique=False)
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    op.create_table('inquiry_products',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('inquiry_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity_requested', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity_requested > 0', name='ck_inquiry_product_quantity_positive'),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inquiry_id', 'product_id', name='uq_inquiry_product')
    )
    op.create_index(op.f('ix_inquiry_products_inquiry_id'), 'inquiry_products', ['inquiry_id'], unique=False)
    op.create_index(op.f('ix_inquiry_products_product_id'), 'inquiry_products', ['product_id'], unique=False)
    op.create_table('product_colors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sort_order >= 0', name='ck_product_color_sort_order_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'name', name='uq_product_color')
    )
    op.create_index(op.f('ix_product_colors_product_id'), 'product_colors', ['product_id'], unique=False)
    op.create_table('product_customizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('is_customizable', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_customizations_product_id'), 'product_customizations', ['product_id'], unique=True)
    op.create_table('product_details',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('garment_type', sa.Text(), nullable=True),
    sa.Column('silhouette', sa.Text(), nullable=True),
    sa.Column('length', sa.Text(), nullable=True),
    sa.Column('fabric', sa.Text(), nullable=True),
    sa.Column('secondary_fabric', sa.Text(), nullable=True),
    sa.Column('lining', sa.Text(), nullable=True),
    sa.Column('neckline', sa.Text(), nullable=True),
    sa.Column('back_style', sa.Text(), nullable=True),
    sa.Column('waistline', sa.Text(), nullable=True),
    sa.Column('sleeve_type', sa.Text(), nullable=True),
    sa.Column('sleeve_length', sa.Text(), nullable=True),
    sa.Column('train', sa.Text(), nullable=True),
    sa.Column('embellishment', sa.Text(), nullable=True),
    sa.Column('closure', sa.Text(), nullable=True),
    sa.Column('internal_support', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_details_product_id'), 'product_details', ['product_id'], unique=True)
    op.create_table('product_measurement_guides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('measurement_unit', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_measurement_guides_product_id'), 'product_measurement_guides', ['product_id'], unique=True)
    op.create_table('product_media',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.Enum('IMAGE', 'VIDEO', name='media_type'), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('alt_text', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sort_order >= 0', name='ck_product_media_sort_order_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_media_product_id'), 'product_media', ['product_id'], unique=False)
    op.create_index('uq_product_media_primary', 'product_media', ['product_id'], unique=True, postgresql_where=sa.text('is_primary = true'))
    op.create_table('product_sizes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sort_order >= 0', name='ck_product_size_sort_order_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'name', name='uq_product_size')
    )
    op.create_index(op.f('ix_product_sizes_product_id'), 'product_sizes', ['product_id'], unique=False)
    op.create_table('product_customization_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customization_id', sa.UUID(), nullable=False),
    sa.Column('option_type', sa.Enum('FABRIC', 'COLOR', 'NECKLINE', 'SLEEVES', 'BACK', 'TRAIN', 'EMBELLISHMENT', 'MEASUREMENTS', 'LENGTH', 'SILHOUETTE', 'FULL_CUSTOM_DESIGN', name='customization_option_type'), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sort_order >= 0', name='ck_product_customization_option_sort_order_non_negative'),
    sa.ForeignKeyConstraint(['customization_id'], ['product_customizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customization_id', 'option_type', name='uq_product_customization_option')
    )
    op.create_index(op.f('ix_product_customization_options_customization_id'), 'product_customization_options', ['customization_id'], unique=False)
    op.create_table('size_measurements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_size_id', sa.UUID(), nullable=False),
    sa.Column('bust', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('waist', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('hips', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('hollow_to_hem', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_size_id'], ['product_sizes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_size_id', name='uq_size_measurement')
    )
    op.create_index(op.f('ix_size_measurements_product_size_id'), 'size_measurements', ['product_size_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_size_measurements_product_size_id'), table_name='size_measurements')
    op.drop_table('size_measurements')
    op.drop_index(op.f('ix_product_customization_options_customization_id'), table_name='product_customization_options')
    op.drop_table('product_customization_options')
    op.drop_index(op.f('ix_product_sizes_product_id'), table_name='product_sizes')
    op.drop_table('product_sizes')
    op.drop_index('uq_product_media_primary', table_name='product_media', postgresql_where=sa.text('is_primary = true'))
    op.drop_index(op.f('ix_product_media_product_id'), table_name='product_media')
    op.drop_table('product_media')
    op.drop_index(op.f('ix_product_measurement_guides_product_id'), table_name='product_measurement_guides')
    op.drop_table('product_measurement_guides')
    op.drop_index(op.f('ix_product_details_product_id'), table_name='product_details')
    op.drop_table('product_details')
    op.drop_index(op.f('ix_product_customizations_product_id'), table_name='product_customizations')
    op.drop_table('product_customizations')
    op.drop_index(op.f('ix_product_colors_product_id'), table_name='product_colors')
    op.drop_table('product_colors')
    op.drop_index(op.f('ix_inquiry_products_product_id'), table_name='inquiry_products')
    op.drop_index(op.f('ix_inquiry_products_inquiry_id'), table_name='inquiry_products')
    op.drop_table('inquiry_products')
    op.drop_index(op.f('ix_products_status'), table_name='products')
    op.drop_index(op.f('ix_products_collection_id'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_brand_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_collections_brand_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_inquiries_status'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_inquiry_type'), table_name='inquiries')
    op.drop_table('inquiries')
    op.drop_index(op.f('ix_content_pages_status'), table_name='content_pages')
    op.drop_index(op.f('ix_content_pages_slug'), table_name='content_pages')
    op.drop_table('content_pages')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_brands_slug'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
